# site settings

title: Dmitry Smyrnov
description: Front-end Developer
taglong: Front-end Developer
tagshort: Front-end Developer
url: https://smyrnovd.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/smyrnovd/smyrnovd.github.io

# author settings

author:
  name: Dmitry S
  email: smyrnovd@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  # facebook: smyrnov
  # github: smyrnovd
  # instagram: dmitrysmyrnov
  linkedin: dmitrysmyrnov
  # stackoverflow: 0000000/username
  # twitter: username
  email: smyrnovd@gmail.com

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
